<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>net.logging.perfect2645</PackageId>
    <Version>2.0.1</Version>
    <Authors>Fawei</Authors>
    <Company>Personal</Company>
    <Product>net.logging</Product>
    <Description>.net logging library.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Copyright>Copyright © 2026 Fawei</Copyright>
    <PackageProjectUrl>https://github.com/perfect2645/Laboratory/tree/main/Utils</PackageProjectUrl>
  	<RepositoryUrl>https://github.com/perfect2645/Laboratory/tree/main/Utils</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <PackageTags>.net tools library - logging</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="log4net.config" />
    <None Remove="README.md" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="serilog.config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="log4net.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="README.md" Pack="true" PackagePath="\">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

</Project>
