namespace LeetCode.numbers
{
    public class PrimeCounter
    {

        #region Generated Code by Copilot

        /// <summary>
        /// generated by Copilot
        /// 计算1到n之间（包含n）有多少个质数
        /// </summary>
        /// <param name="n">上限整数</param>
        /// <returns>质数的数量</returns>
        public int CopilotCountPrimes(int n)
        {
            if (n < 2) return 0;
            int count = 0;
            for (int i = 2; i <= n; i++)
            {
                if (CopilotIsPrime(i)) count++;
            }
            return count;
        }


        /// <summary>
        /// generated by Copilot
        /// </summary>
        /// <param name="number"></param>
        /// <returns></returns>
        private bool CopilotIsPrime(int number)
        {
            if (number < 2) return false;
            if (number == 2) return true;
            if (number % 2 == 0) return false;
            int boundary = (int)Math.Sqrt(number);
            for (int i = 3; i <= boundary; i += 2)
            {
                if (number % i == 0) return false;
            }
            return true;
        }

        #endregion 
    }
}
